# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0379f9086cde6dd5e302c417e1d714b0d0c08ddf56dffaf5591fc83f8afc8ea1a9ec31d1e9ad99e9d35be196d3f8ec7c289724fc9d748fa4de788cd6f0445773

test:
  secret_key_base: e94ba38f930426fccd895de0143ed95c68ae6458b42b0ff13cc6e8bc39ff87f4eab8708b69695b821be553321d0d980a9ea19286a4416ed7b17de01311f9ea0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
